### ISSUE TITLE
Jetson nano CSI camera input and RTSP stream output

### ISSUE THREAD

**Issue by Sutyke** [JustinhoCHN/fall-detection#2]
Hi, Thanks for the example. What I need to change :

1) to run docker container on Jetson Nano with CSI camera input?   
2) to get fall detection video output to RTSP stream output?

**Comment by JustinhoCHN** [comment]
@Sutyke Hi, sorry for late reply.
I suggest you to read the deepstream 5.0 demo apps, which is located at ```/opt/nvidia/deepstream/deepstream-5.0/sources/apps/sample_apps/```, there are many apps for reference.
For the first question, this link may help: [source for CSI camera input](https://forums.developer.nvidia.com/t/source-for-csi-camera-input/107096).
For the second question, you can simply modify the [sink] settings like this:
```
[sink1]
enable=1
#Type - 1=FakeSink 2=EglSink 3=File 4=RTSPStreaming
type=4
#1=h264 2=h265
codec=1
#encoder type 0=Hardware 1=Software
enc-type=0
sync=0
qos=0
bitrate=4000000
#H264 Profile - 0=Baseline 2=Main 4=High
#H265 Profile - 0=Main 1=Main10
profile=0
# set below properties in case of RTSPStreaming
rtsp-port=8554
udp-port=5400
```
Then you can use VLC player to play this rtsp video, address like: ```rtsp://DEVICE_IP:8554/ds-test```
